### PR TITLE
fix loadPgn() to handle pgn without any moves

### LINKED ISSUE #362: loadPgn doesn't work on a pgn without any moves yet
**What**
`chess.loadPgn` doesn't work on a pgn that has no moves yet.

```js
const { Chess } = require('chess.js')

const game = new Chess();
game.header('White', 'id0');
game.header('Black', 'id1');
// game.move('e4'); // uncomment this for loadPgn to work

console.log(game.pgn())
/** output:
[White "id0"]
[Black "id1"]

*/

console.log('trying to load into another game instance')

const gameCpy = new Chess();
const result = gameCpy.loadPgn(game.pgn())
console.log('result:', result) // output: false
```

**Why**
It would be nice to rely solely on the pgn to describe the game, especially when saving the string in a database to track the game to be loaded for future play/moves.

### PR DESCRIPTION
**Pull request by kevo1ution**
fixes #362 

**What**
- handles empty move text by matching headers when move text is empty and by parsing out moves that are empty strings

**Why**
- loadPgn() should handle a PGN that does not contain any moves and only headers

### CODE REVIEW

File: src/chess.ts [hunk 1]
```diff
@@ -1655,7 +1659,7 @@ export class Chess {
     let moves = ms.trim().split(new RegExp(/\s+/))
 
     /* delete empty entries */
-    moves = moves.join(',').replace(/,,+/g, ',').split(',')
+    moves = moves.filter(move => move !== '')
```
Comment (kevo1ution) [inline src/chess.ts:1662]: The current method did not handle the edge case where `moves = ['']`:
```js
moves = [''].join(',').replace(/,,+/g, ',').split(',');
console.log(moves);
// output: ['']
```

The edge case happens when `ms` is empty (in the case where there are no moves):
```js
let ms = '';
console.log(ms.trim().split(new RegExp(/\s+/)));
// output: ['']
```

The solution I went with here is to just use the `.filter` method to remove any empty string from the array.

File: __tests__/load-pgn.test.ts [hunk 2]
```diff
@@ -29,6 +29,21 @@ describe('Load PGN', () => {
...
       expect: true,
     },
+    // GitHub Issue #362 - Load PGN works with no moves
+    {
+      pgn: [
+        '[Event "UrTurn Game Jam"]',
+        '[Round "6"]',
+        '[White "Kevo1ution"]',
+        '[Black "Billy Bob Jr."]',
+        '', // extra newlineChar is expected because pgn() function adds it
```
Comment (kevo1ution) [inline __tests__/load-pgn.test.ts:39]: I left this here because there is a behavior with `pgn()` where it outputs the pgn headers and an extra `newlineChar`. I didn't want to change the behavior of the pgn() function in this PR - It's not clear whether we should or shouldn't change the `pgn()` fn, but either way that change should be in a separate PR.

**Comment by kevo1ution** [comment]
Merry Christmas @jhlywa ! This is ready 🎄 🎅 - looking forward to the review

File: __tests__/load-pgn.test.ts (hunk 2 above)
Comment (jhlywa) [reply __tests__/load-pgn.test.ts:39]: Agree with the separate PR.  Would it be simple enough to just make `.pgn()` eat any trailing `newlineChar`?

**Comment by jhlywa** [comment]
Thanks @kevo1ution and Merry Christmas to you too!
